### ISSUE TITLE
issue with next_batch()

### ISSUE THREAD

**Issue by quaiquai** [analysiscenter/batchflow#276]
Is there a current work around?
error:
Traceback (most recent call last):
  File "/Users/matthewmcquaigue/PycharmProjects/LungCancerDetection/driver.py", line 51, in <module>
    batch = combine_pipeline.next_batch()
  File "/Users/matthewmcquaigue/anaconda3/envs/cv/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py", line 1239, in next_batch
    batch_res = self.next_batch(*args, **kwargs)
  File "/Users/matthewmcquaigue/anaconda3/envs/cv/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py", line 1244, in next_batch
    batch_res = next(self._batch_generator)
StopIteration

**Comment by roman-kh** [comment]
This seems to be related to [radio](https://github.com/analysiscenter/radio).
